### ISSUE TITLE
[FEAT] Extend fallback policy function to allow defaults for certain functions

### ISSUE THREAD

**Issue by veenarm** [Parsifal-M/backstage-opa-plugins#264]
**Is your feature request related to a problem? Please describe.**
No known problems

**Describe the solution you'd like**
policyFallback: 'deny' means that all access is completely locked out if OPA is offline, i'd like some extra flexibility e.g.

```yaml
policyFallback: deny
policyOverrides:  #if policyFallback is invoked
  allow:
    - catalog.permissions.read

so it's deny all by default except generic access/read.
```

Or
```yaml
policyFallback: allow
policyOverrides:  #if policyFallback is invoked
  deny:
    - kubernetes.read

so it's allow all by default except access to the kube plugin etc...
```

**Describe alternatives you've considered**
If OPA is offline currently, its either global yes or global no access.
